<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBookAir.fios-router.home" failures="1" tests="1" name="testRunner.testRunner" time="1.248" errors="0" timestamp="2025-02-08T17:08:16 EST" skipped="0">
  <testcase classname="testRunner.testRunner" name="runScenario" time="1.248">
    <failure message="expected [400] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at stepDefinitions.createUserStepDefinition.admin_receives_status_with_error_message(createUserStepDefinition.java:357)
at âœ½.Admin receives "400" "Bad Request" Status with error message(file:///Users/mathumathibalakrishnan/eclipse/Mathumathi_2024/2025_Team04_RestAssured_BDD/src/test/resources/features/02_createUser.feature:149)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.testRunner -->
